"""empty message

Revision ID: 72328ab6fdf6
Revises: 534ace3d44c4
Create Date: 2020-04-12 16:31:29.074294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72328ab6fdf6'
down_revision = '534ace3d44c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
